//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingCallLog
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsReaded { get; set; }
    }
}
